import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "@/components/ui/sonner";



export const metadata: Metadata = {
  title: "Pharmacy Monitor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <AuthProvider>
          {children}
          <Toaster
            position="top-center"
            richColors
          />

        </AuthProvider>
      </body>
    </html>
  );
}
